                          #########################################
                          #                                       #
                          #=============正式环境配置==============#
                          #                                       #
                          #########################################



#########################################
#
#datasource配置、Druid数据库连接池配置、Druid StatViewServlet监控配置
#
#
#########################################
spring:
  datasource:
  
    # 数据库驱动配置
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.4.5.180:1521/SH10000A
    username: sh10000_wx
    password: dx10000sh_wx
    
    #Druid数据库连接池和监控
    # Druid连接池配置，官方配置参考：https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    druid:
      initial-size: 5
      min-idle: 3
      max-active: 100
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL #select 'x',
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
     
     
      # 配置过滤规则
      # Druid WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*"
        
        
      # 配置监控服务器
      # Druid StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: reaper
        login-password: reaper
        # 添加IP白名单
        allow: "127.0.0.1"
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        deny: ""



#########################################
#
#redis配置
#远程客户端连接需要在 redis-cli.exe/redis-cli.sh 目录下执行
#linux 远程连接客户端  ./redis-cli -h [host] -p [port] -a [password]
#windows 远程连接客户端  redis-cli -h [host] -p [port] -a [password]
#
#########################################
  redis:
    host: 10.144.97.133
    port: 6379
    password: 3edcxsw2-1qaz
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1 
